const $=id=>document.getElementById(id),form=$('weatherForm'),cityInput=$('city'),citySuggestions=$('citySuggestions'),startInput=$('startDate'),endInput=$('endDate'),searchBtn=$('searchBtn'),statusBox=$('status'),locationsBox=$('locations'),locationList=$('locationList'),results=$('results'),savedList=$('savedList'),saveOptionBtn=$('saveOptionBtn'),shareOptionBtn=$('shareOptionBtn'),projectPanel=$('projectPanel'),projectGroups=$('projectGroups'),projectDisplayName=$('projectDisplayName'),projectMode=$('projectMode'),projectNameInput=$('projectNameInput'),projectSwitcher=$('projectSwitcher'),addToProjectBar=$('addToProjectBar'),addProjectSelect=$('addProjectSelect'),addTeamSelect=$('addTeamSelect'),addCurrentQueryBtn=$('addCurrentQueryBtn'),newProjectBtn=$('newProjectBtn'),renameProjectBtn=$('renameProjectBtn'),shareProjectBtn=$('shareProjectBtn'),deleteProjectBtn=$('deleteProjectBtn');
let locationCandidates=[],activeLocationIndex=0,suggestionCandidates=[],suggestionIndex=-1,suggestionTimer=null,suggestionRequest=0,map=null,mapMarker=null,mapReady=false,mapMoveRequest=0,currentLocation=null;const SAVED_KEY='internationalWeatherSavedOptionsV1';
function localISO(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
const today=new Date();today.setHours(12,0,0,0);const maxDate=new Date(today);maxDate.setDate(maxDate.getDate()+15);const defaultEnd=new Date(today);defaultEnd.setDate(defaultEnd.getDate()+6);
[startInput,endInput].forEach(el=>{el.min=localISO(today)});startInput.value=localISO(today);endInput.value=localISO(defaultEnd);
function setStatus(message,type='info',loading=false){statusBox.className=`status show ${type}`;statusBox.innerHTML=`${loading?'<span class="spinner" aria-hidden="true"></span>':''}<span>${message}</span>`}
function clearStatus(){statusBox.className='status';statusBox.textContent=''}function setBusy(busy){searchBtn.disabled=busy;searchBtn.textContent=busy?'查詢中…':'查詢天氣'}
function validateDates(){if(!startInput.value||!endInput.value)throw new Error('請選擇完整的日期區間。');const start=new Date(`${startInput.value}T12:00:00`),end=new Date(`${endInput.value}T12:00:00`);if(start>end)throw new Error('結束日期不可早於起始日期。')}
const CITY_ALIASES={'羅馬':['Rome','Roma'],'威尼斯':['Venice','Venezia'],'佛羅倫斯':['Florence','Firenze'],'米蘭':['Milan','Milano'],'拿坡里':['Naples','Napoli'],'那不勒斯':['Naples','Napoli'],'杜林':['Turin','Torino'],'波隆那':['Bologna'],'比薩':['Pisa'],'維洛納':['Verona'],'西恩納':['Siena'],'熱那亞':['Genoa','Genova'],'慕尼黑':['Munich','München'],'科隆':['Cologne','Köln'],'紐倫堡':['Nuremberg','Nürnberg'],'法蘭克福':['Frankfurt'],'漢堡':['Hamburg'],'柏林':['Berlin'],'德勒斯登':['Dresden'],'維也納':['Vienna','Wien'],'薩爾斯堡':['Salzburg'],'布拉格':['Prague','Praha'],'布達佩斯':['Budapest'],'華沙':['Warsaw','Warszawa'],'克拉科夫':['Krakow','Kraków'],'雅典':['Athens','Athina'],'伊斯坦堡':['Istanbul','İstanbul'],'蘇黎世':['Zurich','Zürich'],'日內瓦':['Geneva','Genève'],'布魯塞爾':['Brussels','Bruxelles'],'阿姆斯特丹':['Amsterdam'],'哥本哈根':['Copenhagen','København'],'斯德哥爾摩':['Stockholm'],'奧斯陸':['Oslo'],'赫爾辛基':['Helsinki'],'雷克雅維克':['Reykjavik'],'里斯本':['Lisbon','Lisboa'],'波多':['Porto'],'塞維亞':['Seville','Sevilla'],'馬德里':['Madrid'],'巴塞隆納':['Barcelona'],'巴塞羅那':['Barcelona'],'瓦倫西亞':['Valencia'],'馬拉加':['Malaga','Málaga'],'倫敦':['London'],'愛丁堡':['Edinburgh'],'都柏林':['Dublin'],'巴黎':['Paris'],'里昂':['Lyon'],'尼斯':['Nice'],'馬賽':['Marseille'],'波爾多':['Bordeaux'],'紐約':['New York'],'洛杉磯':['Los Angeles'],'舊金山':['San Francisco'],'拉斯維加斯':['Las Vegas'],'芝加哥':['Chicago'],'波士頓':['Boston'],'西雅圖':['Seattle'],'華盛頓':['Washington'],'東京':['Tokyo'],'大阪':['Osaka'],'京都':['Kyoto'],'名古屋':['Nagoya'],'福岡':['Fukuoka'],'札幌':['Sapporo'],'仙台':['Sendai'],'廣島':['Hiroshima'],'熊本':['Kumamoto'],'沖繩':['Naha','Okinawa'],'首爾':['Seoul'],'釜山':['Busan'],'濟州':['Jeju'],'曼谷':['Bangkok'],'清邁':['Chiang Mai'],'新加坡':['Singapore'],'吉隆坡':['Kuala Lumpur'],'峇里島':['Denpasar','Bali'],'河內':['Hanoi'],'胡志明市':['Ho Chi Minh City','Saigon'],'雪梨':['Sydney'],'悉尼':['Sydney'],'墨爾本':['Melbourne'],'布里斯本':['Brisbane'],'奧克蘭':['Auckland'],'基督城':['Christchurch'],'杜拜':['Dubai'],'阿布達比':['Abu Dhabi'],'開羅':['Cairo']};
function cityQueryVariants(city){const q=city.trim(),compact=q.replace(/[臺台]/g,'台');const variants=[q,...(CITY_ALIASES[q]||[]),...(CITY_ALIASES[compact]||[])];const first=q.split(/[，,、\s]+/)[0];if(first&&first!==q)variants.push(first,...(CITY_ALIASES[first]||[]));return [...new Set(variants.filter(Boolean))]}
async function geocodeOnce(query,language='zh',count=8){const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query)}&count=${count}&language=${language}&format=json`);if(!response.ok)throw new Error('城市搜尋服務暫時無法連線。');const data=await response.json();return data.results||[]}
function mergeLocations(groups){const seen=new Set(),merged=[];groups.flat().forEach(loc=>{const key=loc.id?`id:${loc.id}`:`${Number(loc.latitude).toFixed(4)},${Number(loc.longitude).toFixed(4)}`;if(!seen.has(key)){seen.add(key);merged.push(loc)}});return merged}
async function geocodeCity(city){const variants=cityQueryVariants(city),groups=[];for(const query of variants){const [zh,en]=await Promise.all([geocodeOnce(query,'zh',8).catch(()=>[]),geocodeOnce(query,'en',8).catch(()=>[])]);groups.push(zh,en);if(mergeLocations(groups).length>=10)break}return mergeLocations(groups).slice(0,12)}
function fullLocationName(loc){return[loc.name,loc.admin1,loc.country].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join('，')}
function hideSuggestions(){citySuggestions.className='autocomplete';citySuggestions.innerHTML='';suggestionCandidates=[];suggestionIndex=-1;cityInput.setAttribute('aria-expanded','false')}
function renderSuggestions(items){suggestionCandidates=items;suggestionIndex=-1;if(!items.length){hideSuggestions();return}citySuggestions.innerHTML=items.map((loc,i)=>{const main=loc.name||'',sub=[loc.admin1,loc.country].filter(Boolean).filter((v,j,a)=>a.indexOf(v)===j&&v!==main).join('，');return `<button type="button" class="autocomplete-item" role="option" data-index="${i}"><span class="autocomplete-main">${main}</span><span class="autocomplete-sub">${sub||' '}</span></button>`}).join('');citySuggestions.className='autocomplete show';cityInput.setAttribute('aria-expanded','true');citySuggestions.querySelectorAll('.autocomplete-item').forEach(btn=>btn.addEventListener('mousedown',e=>{e.preventDefault();selectSuggestion(Number(btn.dataset.index))}))}
function selectSuggestion(index){const loc=suggestionCandidates[index];if(!loc)return;cityInput.value=fullLocationName(loc);hideSuggestions();cityInput.focus()}
function moveSuggestion(step){const buttons=[...citySuggestions.querySelectorAll('.autocomplete-item')];if(!buttons.length)return;suggestionIndex=(suggestionIndex+step+buttons.length)%buttons.length;buttons.forEach((b,i)=>b.classList.toggle('active',i===suggestionIndex));buttons[suggestionIndex].scrollIntoView({block:'nearest'})}
cityInput.addEventListener('input',()=>{clearTimeout(suggestionTimer);const query=cityInput.value.trim();if(query.length<2){hideSuggestions();return}const request=++suggestionRequest;suggestionTimer=setTimeout(async()=>{try{const items=await geocodeCity(query);if(request!==suggestionRequest||cityInput.value.trim()!==query)return;renderSuggestions(items.slice(0,8))}catch{if(request===suggestionRequest)hideSuggestions()}},280)});
cityInput.addEventListener('keydown',event=>{if(!citySuggestions.classList.contains('show'))return;if(event.key==='ArrowDown'){event.preventDefault();moveSuggestion(1)}else if(event.key==='ArrowUp'){event.preventDefault();moveSuggestion(-1)}else if(event.key==='Enter'&&suggestionIndex>=0){event.preventDefault();selectSuggestion(suggestionIndex)}else if(event.key==='Escape'){hideSuggestions()}});
cityInput.addEventListener('blur',()=>setTimeout(hideSuggestions,120));
function renderLocations(){locationList.innerHTML='';if(locationCandidates.length<=1){locationsBox.className='locations';return}locationCandidates.forEach((loc,index)=>{const button=document.createElement('button');button.type='button';button.className=`location-chip${index===activeLocationIndex?' active':''}`;button.textContent=fullLocationName(loc);button.addEventListener('click',()=>loadWeather(index));locationList.appendChild(button)});locationsBox.className='locations show'}
async function fetchWeather(loc){const requestedStart=new Date(`${startInput.value}T12:00:00`);const requestedEnd=new Date(`${endInput.value}T12:00:00`);const availableStart=new Date(today);const availableEnd=new Date(maxDate);const actualStart=new Date(Math.max(requestedStart.getTime(),availableStart.getTime()));const actualEnd=new Date(Math.min(requestedEnd.getTime(),availableEnd.getTime()));if(actualStart>actualEnd){return{daily:{time:[]},timezone:loc.timezone||'auto',timezone_abbreviation:'',_requested:{start:startInput.value,end:endInput.value},_available:{start:localISO(availableStart),end:localISO(availableEnd)},_partial:true}}const daily='temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset';const url=`https://api.open-meteo.com/v1/forecast?latitude=${loc.latitude}&longitude=${loc.longitude}&daily=${daily}&timezone=auto&start_date=${localISO(actualStart)}&end_date=${localISO(actualEnd)}`;const response=await fetch(url);if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.reason||'天氣服務暫時無法取得資料。')}const data=await response.json();data._requested={start:startInput.value,end:endInput.value};data._available={start:localISO(availableStart),end:localISO(availableEnd)};data._partial=(localISO(actualStart)!==startInput.value||localISO(actualEnd)!==endInput.value);return data}
function enumerateDates(startISO,endISO){const out=[],d=new Date(`${startISO}T12:00:00`),end=new Date(`${endISO}T12:00:00`);while(d<=end){out.push(localISO(d));d.setDate(d.getDate()+1)}return out}
function weatherIndexMap(daily){const map=new Map();(daily?.time||[]).forEach((d,i)=>map.set(d,i));return map}
function dateParts(iso){const date=new Date(`${iso}T12:00:00`);return{main:new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric'}).format(date),sub:new Intl.DateTimeFormat('zh-TW',{weekday:'long'}).format(date)}}
function timeOnly(value){return!value?'—':value.includes('T')?value.split('T')[1].slice(0,5):value}function safeValue(arr,index,suffix=''){const value=arr&&arr[index];return value===null||value===undefined?'—':`${Math.round(value)}${suffix}`}
function ensureMap(){if(mapReady)return true;if(typeof L==='undefined'){setStatus('互動地圖元件載入失敗，請確認網路連線後重新整理。','error');return false}map=L.map('cityMap',{zoomControl:true,attributionControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.on('click',e=>moveWeatherMarker(e.latlng.lat,e.latlng.lng,true));mapReady=true;return true}
function renderCityMap(loc){const lat=Number(loc.latitude),lon=Number(loc.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!ensureMap())return;$('mapTitle').textContent=`${fullLocationName(loc)}・位置`;if(!mapMarker){mapMarker=L.marker([lat,lon],{draggable:true,title:'拖曳至要查詢氣象的位置'}).addTo(map);mapMarker.on('dragend',()=>{const p=mapMarker.getLatLng();moveWeatherMarker(p.lat,p.lng,false)})}else mapMarker.setLatLng([lat,lon]);map.setView([lat,lon],10,{animate:false});setTimeout(()=>map.invalidateSize(),0)}
async function moveWeatherMarker(lat,lon,recenter=false){const request=++mapMoveRequest;if(mapMarker)mapMarker.setLatLng([lat,lon]);if(recenter&&map)map.panTo([lat,lon]);const customLoc={name:'地圖選取位置',admin1:`${Number(lat).toFixed(4)}, ${Number(lon).toFixed(4)}`,country:'',latitude:Number(lat),longitude:Number(lon),timezone:'auto'};$('mapTitle').textContent=`地圖選取位置・${Number(lat).toFixed(4)}, ${Number(lon).toFixed(4)}`;setStatus('正在查詢圖標位置的氣象…','info',true);setBusy(true);try{validateDates();const data=await fetchWeather(customLoc);if(request!==mapMoveRequest)return;renderWeather(customLoc,data);clearStatus()}catch(error){if(request===mapMoveRequest)setStatus(error.message||'圖標位置氣象查詢失敗。','error')}finally{if(request===mapMoveRequest)setBusy(false)}}
function renderWeather(loc,data){currentLocation={...loc};const daily=data.daily;if(!daily||!daily.time||!daily.time.length){currentLocation={...loc};$('cityName').textContent=fullLocationName(loc)||loc.name;$('cityMeta').textContent=`座標 ${Number(loc.latitude).toFixed(3)}, ${Number(loc.longitude).toFixed(3)}・目前可取得的預報日期為 ${data._available?.start||localISO(today)} ～ ${data._available?.end||localISO(maxDate)}`;$('updated').textContent=`查詢時間：${new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}`;$('weatherRows').innerHTML=enumerateDates(data._requested?.start||startInput.value,data._requested?.end||endInput.value).map(date=>{const parts=dateParts(date);return `<tr><td><div class="date-main">${parts.main}</div><div class="date-sub">${parts.sub}</div></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td></tr>`}).join('');renderSourceLinks(loc);results.className='results show';renderCityMap(loc);updateMemoryIcon();renderAddToProjectBar();return}$('cityName').textContent=fullLocationName(loc);$('cityMeta').textContent=`座標 ${Number(loc.latitude).toFixed(3)}, ${Number(loc.longitude).toFixed(3)}・時區 ${data.timezone_abbreviation||data.timezone||loc.timezone}${data._partial?`・指定期間 ${data._requested.start} ～ ${data._requested.end}，目前顯示有資料的 ${data.daily.time[0]} ～ ${data.daily.time[data.daily.time.length-1]}`:''}`;$('updated').textContent=`查詢時間：${new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}`;renderCityMap(loc);const allDates=enumerateDates(data._requested?.start||startInput.value,data._requested?.end||endInput.value),idxMap=weatherIndexMap(daily);$('weatherRows').innerHTML=allDates.map(date=>{const parts=dateParts(date),i=idxMap.get(date);if(i===undefined){return `<tr><td><div class="date-main">${parts.main}</div><div class="date-sub">${parts.sub}</div></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td><td class="no-weather"></td></tr>`}const rain=daily.precipitation_probability_max?.[i],rainNumber=Number.isFinite(rain)?Math.max(0,Math.min(100,rain)):0;return `<tr><td><div class="date-main">${parts.main}</div><div class="date-sub">${parts.sub}</div></td><td class="temp-high">${safeValue(daily.temperature_2m_max,i,'°C')}</td><td class="temp-low">${safeValue(daily.temperature_2m_min,i,'°C')}</td><td><div class="rain-wrap"><strong>${safeValue(daily.precipitation_probability_max,i,'%')}</strong><span class="rain-track"><span class="rain-fill" style="width:${rainNumber}%"></span></span></div></td><td><span class="sun-time"><i class="sun-dot"></i>${timeOnly(daily.sunrise?.[i])}</span></td><td><span class="sun-time"><i class="moon-dot"></i>${timeOnly(daily.sunset?.[i])}</span></td></tr>`}).join('');renderSourceLinks(loc);results.className='results show';updateMemoryIcon();renderAddToProjectBar()}
function shareState(loc=currentLocation){if(!loc)return null;return{name:fullLocationName(loc)||loc.name||'分享位置',lat:Number(loc.latitude),lon:Number(loc.longitude),start:startInput.value,end:endInput.value}}
function buildShareURL(state=shareState()){if(!state)return '';const base=location.href.split('#')[0].split('?')[0],url=new URL(base);url.searchParams.set('weather','1');url.searchParams.set('name',state.name);url.searchParams.set('lat',Number(state.lat).toFixed(6));url.searchParams.set('lon',Number(state.lon).toFixed(6));url.searchParams.set('start',state.start);url.searchParams.set('end',state.end);return url.toString()}
async function copyText(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true}const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}catch{return false}}
async function shareCurrent(){const state=shareState();if(!state){setStatus('請先完成一次地點與日期查詢。','error');return}const url=buildShareURL(state);if(navigator.share&&location.protocol!=='file:'){try{await navigator.share({title:`${state.name} 天氣`,text:`${state.name} ${state.start}～${state.end} 天氣`,url});return}catch(e){if(e?.name==='AbortError')return}}const ok=await copyText(url);if(location.protocol==='file:'){setStatus(ok?'分享連結已複製；目前是本機 HTML，對方必須有相同網頁檔案。部署到網站後，此連結即可直接對外使用。':'無法自動複製連結，請先將此 HTML 部署到網站再分享。','info')}else setStatus(ok?'分享連結已複製到剪貼簿。':'無法自動複製，請從瀏覽器網址列複製目前分享網址。',ok?'info':'error')}