let activeWeatherQuery=null,weatherQueryId=0;
async function runWeatherQuery(locationOrResolver,message,scroll=false){
  activeWeatherQuery?.controller.abort();
  const controller=new AbortController();
  const query={id:++weatherQueryId,controller,signal:controller.signal,start:startInput.value,end:endInput.value};
  activeWeatherQuery=query;
  window.dispatchEvent(new Event('weather-query-start'));
  setBusy(true);setStatus(message,'info',true);
  try{
    validateDates();
    const loc=typeof locationOrResolver==='function'?await locationOrResolver(query):locationOrResolver;
    WeatherRequests.check(query.signal);
    const data=await fetchWeather(loc,query);
    if(activeWeatherQuery!==query||query.signal.aborted)return;
    renderWeather(loc,data);
    const warnings=data._warnings||[];
    if(warnings.length)setStatus(warnings.join(' '),'info');else clearStatus();
    if(scroll)results.scrollIntoView({behavior:'smooth',block:'start'});
    return data;
  }catch(error){
    if(activeWeatherQuery===query&&!query.signal.aborted)setStatus(error.message||'查詢失敗，請稍後再試。','error');
  }finally{
    if(activeWeatherQuery===query)setBusy(false);
  }
}
function getSaved(){try{return JSON.parse(localStorage.getItem(SAVED_KEY)||'[]')}catch{return []}}
function setSaved(items){localStorage.setItem(SAVED_KEY,JSON.stringify(items));renderSavedOptions()}
function saveCurrent(){const state=shareState();if(!state){setStatus('請先完成一次地點與日期查詢。','error');return}let items=getSaved();const key=`${state.lat.toFixed(5)},${state.lon.toFixed(5)}|${state.start}|${state.end}`;items=items.filter(x=>x.key!==key);items.unshift({...state,key,created:Date.now()});setSaved(items.slice(0,30));setStatus(`已記憶「${state.name}」這組地點與日期。`,'info')}
function deleteSaved(key){setSaved(getSaved().filter(x=>x.key!==key))}
async function copySaved(key){const item=getSaved().find(x=>x.key===key);if(!item)return;const ok=await copyText(buildShareURL(item));setStatus(ok?'這個選項的分享連結已複製。':'無法自動複製分享連結。',ok?'info':'error')}
async function loadSaved(item){startInput.value=item.start;endInput.value=item.end;cityInput.value=item.name;const loc={name:item.name,admin1:'',country:'',latitude:Number(item.lat),longitude:Number(item.lon),timezone:'auto'};return runWeatherQuery(loc,'正在載入已記憶的天氣選項…',true)}
function renderSavedOptions(){if(!savedList)return;const items=getSaved();if(!items.length){savedList.innerHTML='<div class="saved-empty">尚未記憶任何地點與日期。完成查詢後可按「記憶此選項」。</div>';return}savedList.innerHTML=items.map((x,i)=>`<div class="saved-item"><div class="saved-info"><div class="saved-name">${escapeHTML(x.name)}</div><div class="saved-meta">${escapeHTML(x.start)} ～ ${escapeHTML(x.end)}・${Number(x.lat).toFixed(4)}, ${Number(x.lon).toFixed(4)}</div></div><div class="saved-actions"><button class="mini" type="button" data-load="${i}">載入</button><button class="mini" type="button" data-copy="${escapeAttr(x.key)}">分享</button><button class="mini danger" type="button" data-delete="${escapeAttr(x.key)}">刪除</button></div></div>`).join('');savedList.querySelectorAll('[data-load]').forEach(b=>b.addEventListener('click',()=>loadSaved(items[Number(b.dataset.load)])));savedList.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copySaved(b.dataset.copy)));savedList.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteSaved(b.dataset.delete)))}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escapeAttr(v){return escapeHTML(v)}
async function restoreSharedLink(){const p=new URLSearchParams(location.search);if(p.get('weather')!=='1')return;const lat=Number(p.get('lat')),lon=Number(p.get('lon')),name=p.get('name')||'分享位置',start=p.get('start'),end=p.get('end');if(!p.has('lat')||!p.has('lon')||!Number.isFinite(lat)||!Number.isFinite(lon)||!start||!end)return;startInput.value=start;endInput.value=end;cityInput.value=name;return runWeatherQuery({name,admin1:'',country:'',latitude:lat,longitude:lon,timezone:'auto'},'正在開啟分享的天氣選項…')}
saveOptionBtn.addEventListener('click',saveCurrent);shareOptionBtn.addEventListener('click',shareCurrent);addProjectSelect?.addEventListener('change',refreshAddTeamSelect);addCurrentQueryBtn?.addEventListener('click',addCurrentQueryToSelected);
const PROJECTS_KEY='internationalWeatherProjectsV2',OPTIONAL_TEAMS=['先遣A','先遣B','先遣C'],TEAM_ORDER=['本隊','先遣A','先遣B','先遣C'];let projectState={projects:[],activeId:null},readonlyProject=null,isReadonly=false;
function uuid(){return (crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`)}
function readProjects(){try{let v=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'null');if(v&&Array.isArray(v.projects)){if(!v.activeId&&v.projects[0])v.activeId=v.projects[0].id;return v}const old=JSON.parse(localStorage.getItem('internationalWeatherProjectsV1')||'null');if(old&&Array.isArray(old.projects)){const migrated={projects:old.projects.map(normalizeProject).filter(Boolean),activeId:old.activeId||null};localStorage.setItem(PROJECTS_KEY,JSON.stringify(migrated));return migrated}}catch{}return{projects:[],activeId:null}}
function writeProjects(){localStorage.setItem(PROJECTS_KEY,JSON.stringify(projectState))}
function activeProject(){return isReadonly?readonlyProject:projectState.projects.find(p=>p.id===projectState.activeId)||null}
function newProject(name){name=(name||'').trim();if(!name){setStatus('請先輸入專案名稱。','error');return}const p={id:uuid(),name,teams:{'本隊':[]},created:Date.now()};projectState.projects.unshift(p);projectState.activeId=p.id;writeProjects();renderProject();setStatus(`已建立專案「${name}」。可依需要新增先遣A、B或C。`,'info')}
function normalizeProject(p){if(!p||typeof p!=='object')return null;const out={id:p.id||uuid(),name:String(p.name||'分享專案'),teams:{'本隊':[]}};const sourceTeams=p.teams||{};for(const t of TEAM_ORDER){if(t!=='本隊'&&!Object.prototype.hasOwnProperty.call(sourceTeams,t))continue;const arr=Array.isArray(sourceTeams[t])?sourceTeams[t]:[];out.teams[t]=arr.map(x=>{let end=String(x.end||'');if(!end&&x.start&&x.days)end=projectEntryEnd(String(x.start),Number(x.days));return{id:x.id||uuid(),city:String(x.city||''),start:String(x.start||''),end,lat:Number.isFinite(Number(x.lat))?Number(x.lat):null,lon:Number.isFinite(Number(x.lon))?Number(x.lon):null,label:String(x.label||x.city||'')}})}return out}
function projectEntryEnd(start,days){const d=new Date(`${start}T12:00:00`);if(Number.isNaN(d.getTime()))return '';d.setDate(d.getDate()+Math.max(1,Number(days)||1)-1);return localISO(d)}
function activeTeams(p){return TEAM_ORDER.filter(t=>t==='本隊'||Object.prototype.hasOwnProperty.call(p.teams||{},t))}
function addTeam(team){if(isReadonly||!OPTIONAL_TEAMS.includes(team))return;const p=activeProject();if(!p){setStatus('請先建立專案。','error');return}if(Object.prototype.hasOwnProperty.call(p.teams,team)){setStatus(`${team} 已經存在。`,'info');return}p.teams[team]=[];writeProjects();renderProject();renderAddToProjectBar();setStatus(`已新增 ${team}。`,'info')}
function removeTeam(team){if(isReadonly||!OPTIONAL_TEAMS.includes(team))return;const p=activeProject();if(!p||!Object.prototype.hasOwnProperty.call(p.teams,team))return;delete p.teams[team];writeProjects();renderProject();renderAddToProjectBar();setStatus(`已刪除 ${team}。`,'info')}
function renderProjectSwitcher(){if(!projectSwitcher)return;if(isReadonly){projectSwitcher.innerHTML='';return}if(!projectState.projects.length){projectSwitcher.innerHTML='';return}projectSwitcher.innerHTML=projectState.projects.map(p=>`<button type="button" class="project-switch-btn${p.id===projectState.activeId?' active':''}" data-project-switch="${escapeAttr(p.id)}">${escapeHTML(p.name)}</button>`).join('');projectSwitcher.querySelectorAll('[data-project-switch]').forEach(btn=>btn.addEventListener('click',()=>{projectState.activeId=btn.dataset.projectSwitch;writeProjects();renderProject();renderAddToProjectBar()}))}
function renderProject(){const p=activeProject();document.body.classList.toggle('readonly',isReadonly);renderProjectSwitcher();if(!p){projectDisplayName.textContent='天氣專案';projectMode.textContent=isReadonly?'唯讀分享':'尚未建立';projectGroups.innerHTML='<div class="team-empty">尚未建立專案。輸入專案名稱後按「建立專案」。</div>';renderAddToProjectBar();return}projectDisplayName.textContent=p.name;projectMode.textContent=isReadonly?'唯讀分享':'我的專案';if(!isReadonly)projectNameInput.value=p.name;projectGroups.innerHTML=activeTeams(p).map(team=>{const items=p.teams?.[team]||[];const removeTeamBtn=(!isReadonly&&team!=='本隊')?`<button class="team-remove owner-only" type="button" data-remove-team-block="${team}">刪除${team}</button>`:'';const list=items.length?items.map(x=>`<div class="project-entry"><button class="entry-main" type="button" data-open-team="${team}" data-open-id="${escapeAttr(x.id)}"><div class="entry-city">${escapeHTML(x.label||x.city)}</div><div class="entry-date">${escapeHTML(x.start)} ～ ${escapeHTML(x.end)}</div></button><button class="entry-remove owner-only" type="button" data-remove-entry-team="${team}" data-remove-id="${escapeAttr(x.id)}" title="刪除城市">×</button></div>`).join(''):'<div class="team-empty">尚未加入城市</div>';return `<div class="team-card"><div class="team-head"><h3>${team}</h3><div><span class="team-count">${items.length} 個城市</span>${removeTeamBtn}</div></div><div class="team-list">${list}</div></div>`}).join('');projectGroups.querySelectorAll('[data-open-id]').forEach(b=>b.addEventListener('click',()=>openProjectEntry(b.dataset.openTeam,b.dataset.openId)));projectGroups.querySelectorAll('[data-remove-id]').forEach(b=>b.addEventListener('click',()=>removeProjectEntry(b.dataset.removeEntryTeam,b.dataset.removeId)));projectGroups.querySelectorAll('[data-remove-team-block]').forEach(b=>b.addEventListener('click',()=>removeTeam(b.dataset.removeTeamBlock)));renderAddToProjectBar()}
function removeProjectEntry(team,id){if(isReadonly)return;const p=activeProject();if(!p||!p.teams?.[team])return;p.teams[team]=p.teams[team].filter(x=>x.id!==id);writeProjects();renderProject()}
async function openProjectEntry(team,id){const p=activeProject();if(!p)return;const x=(p.teams?.[team]||[]).find(v=>v.id===id);if(!x)return;startInput.value=x.start;endInput.value=x.end;cityInput.value=x.label||x.city;return runWeatherQuery(async query=>{const loc={name:x.label||x.city,admin1:'',country:'',latitude:x.lat,longitude:x.lon,timezone:'auto'};if(x.lat===null||x.lon===null||!Number.isFinite(Number(x.lat))||!Number.isFinite(Number(x.lon))){const found=await geocodeCity(x.city,query.signal);if(!found.length)throw new Error('找不到這個城市。');Object.assign(loc,found[0])}return loc},`正在開啟 ${team}・${x.label||x.city}…`,true)}
function updateMemoryIcon(){if(!saveOptionBtn)return;const s=typeof shareState==='function'?shareState():null;if(!s){saveOptionBtn.textContent='☆';saveOptionBtn.title='儲存目前查詢';saveOptionBtn.setAttribute('aria-label','儲存目前查詢');return}const saved=getSaved();const exists=Array.isArray(saved)&&saved.some(x=>Math.abs(Number(x.lat)-Number(s.lat))<0.000001&&Math.abs(Number(x.lon)-Number(s.lon))<0.000001&&x.start===s.start&&x.end===s.end);saveOptionBtn.classList.toggle('saved',exists);saveOptionBtn.textContent=exists?'★':'☆';saveOptionBtn.title=exists?'已儲存':'儲存目前查詢';saveOptionBtn.setAttribute('aria-label',saveOptionBtn.title)}
function renderAddToProjectBar(){if(!addToProjectBar)return;const s=shareState();if(isReadonly||!s){addToProjectBar.classList.remove('show');return}addToProjectBar.classList.add('show');if(!projectState.projects.length){addProjectSelect.innerHTML='<option value="">尚未建立專案</option>';addTeamSelect.innerHTML='<option value="">—</option>';addCurrentQueryBtn.disabled=true;return}addProjectSelect.innerHTML=projectState.projects.map(p=>`<option value="${escapeAttr(p.id)}"${p.id===projectState.activeId?' selected':''}>${escapeHTML(p.name)}</option>`).join('');const selectedProject=projectState.projects.find(p=>p.id===addProjectSelect.value)||activeProject()||projectState.projects[0];if(selectedProject)addProjectSelect.value=selectedProject.id;const teams=selectedProject?activeTeams(selectedProject):[];addTeamSelect.innerHTML=teams.map(t=>`<option value="${t}">${t}</option>`).join('');addCurrentQueryBtn.disabled=!selectedProject||!teams.length}
function refreshAddTeamSelect(){const p=projectState.projects.find(x=>x.id===addProjectSelect.value);const teams=p?activeTeams(p):[];addTeamSelect.innerHTML=teams.map(t=>`<option value="${t}">${t}</option>`).join('');addCurrentQueryBtn.disabled=!p||!teams.length}
function addCurrentQueryToSelected(){if(isReadonly)return;const s=shareState();const p=projectState.projects.find(x=>x.id===addProjectSelect.value);const team=addTeamSelect.value;if(!s){setStatus('請先完成天氣查詢。','error');return}if(!p){setStatus('請先選擇要加入的專案。','error');return}if(!p.teams?.[team]){setStatus('請先選擇有效的類別。','error');return}p.teams[team].push({id:uuid(),city:s.name,start:s.start,end:s.end,lat:Number(s.lat),lon:Number(s.lon),label:s.name});projectState.activeId=p.id;writeProjects();renderProject();setStatus(`已加入「${p.name}」的 ${team}：${s.name}（${s.start} ～ ${s.end}）。`,'info')}
function encodeProject(p){const json=JSON.stringify(normalizeProject(p));const bytes=new TextEncoder().encode(json);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function decodeProject(s){try{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)),json=new TextDecoder().decode(bytes);return normalizeProject(JSON.parse(json))}catch{return null}}
function buildProjectShareURL(){const p=activeProject();if(!p)return'';const base=location.href.split('#')[0].split('?')[0],u=new URL(base);u.searchParams.set('project',encodeProject(p));u.searchParams.set('readonly','1');return u.toString()}
async function shareProject(){const p=activeProject();if(!p){setStatus('請先建立專案。','error');return}const url=buildProjectShareURL();if(navigator.share&&location.protocol!=='file:'){try{await navigator.share({title:p.name,text:p.name,url});return}catch(e){if(e?.name==='AbortError')return}}const ok=await copyText(url);setStatus(ok?`「${p.name}」唯讀分享連結已複製。對方只會看到這個專案。`:'無法自動複製專案分享連結。',ok?'info':'error')}
function initProjectMode(){const q=new URLSearchParams(location.search),encoded=q.get('project');if(encoded&&q.get('readonly')==='1'){const p=decodeProject(encoded);if(p){isReadonly=true;readonlyProject=p;renderProject();return}}projectState=readProjects();renderProject()}
newProjectBtn.addEventListener('click',()=>newProject(projectNameInput.value));renameProjectBtn.addEventListener('click',()=>{if(isReadonly)return;const p=activeProject(),name=projectNameInput.value.trim();if(!p||!name)return;p.name=name;writeProjects();renderProject();setStatus('專案名稱已更新。','info')});shareProjectBtn.addEventListener('click',shareProject);deleteProjectBtn.addEventListener('click',()=>{if(isReadonly)return;const p=activeProject();if(!p)return;projectState.projects=projectState.projects.filter(x=>x.id!==p.id);projectState.activeId=projectState.projects[0]?.id||null;writeProjects();renderProject();setStatus('專案已刪除。','info')});document.querySelectorAll('[data-add-team]').forEach(b=>b.addEventListener('click',()=>addTeam(b.dataset.addTeam)));
function renderSourceLinks(loc){const city=encodeURIComponent(`${loc.name} ${loc.country||''}`),lat=Number(loc.latitude).toFixed(4),lon=Number(loc.longitude).toFixed(4),links=[['Windy',`https://www.windy.com/${lat}/${lon}?${lat},${lon},8`],['meteoblue',`https://www.meteoblue.com/en/weather/search/search?query=${city}`],['Weather.com',`https://weather.com/weather/today/l/${lat},${lon}`],['AccuWeather',`https://www.accuweather.com/en/search-locations?query=${city}`],['WMO官方資料','https://worldweather.wmo.int/']];$('sourceLinks').innerHTML=links.map(([name,url])=>`<a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}
async function loadWeather(index){const loc=locationCandidates[index];if(!loc)return;activeLocationIndex=index;renderLocations();return runWeatherQuery(loc,'正在取得天氣資料…')}
form.addEventListener('submit',async event=>{event.preventDefault();hideSuggestions();results.className='results';locationsBox.className='locations';const city=cityInput.value.trim();await runWeatherQuery(async query=>{if(city.length<2)throw new Error('請輸入至少2個字的城市名稱。');const found=await geocodeCity(city,query.signal);WeatherRequests.check(query.signal);if(!found.length)throw new Error('仍找不到這個城市。可嘗試加入國家名稱，例如「巴黎 法國」或輸入當地英文名稱。');locationCandidates=found;activeLocationIndex=0;renderLocations();return found[0]},'正在搜尋城市…')});
renderSavedOptions();initProjectMode();restoreSharedLink();
